"""The sandbox: a nested Hyprland session shown as one window on the host.

The nested compositor has its own seat, so its cursor and keyboard focus are
independent of the user's. The host window is parked on a hidden workspace
with render_unfocused set, which keeps the sandbox rendering (and therefore
screenshots working) while nobody is looking at it.
"""

import json
import os
import shutil
import signal
import subprocess
import time
from pathlib import Path
from string import Template

from . import config as settings
from . import cursor
from .hypr import Hypr, HyprError, instances, lua_table, require_host

PARK_WORKSPACE = "agentdesk"
HOST_RULE = "agentdesk-host"

SANDBOX_CONFIG = Template("""\
-- Generated by agentdesk on every start; edits here are overwritten.
hl.monitor({ output = "", mode = "${width}x${height}", position = "0x0", scale = 1 })

hl.config({
  general = {
    gaps_in = 4,
    gaps_out = 8,
    border_size = 2,
    col = { active_border = "rgb(${accent})", inactive_border = "rgba(58596eaa)" },
  },
  decoration = { rounding = 8, shadow = { enabled = false }, blur = { enabled = false } },
  animations = { enabled = false },
  input = { kb_layout = ${kb_layout}, kb_variant = ${kb_variant}, follow_mouse = 2 },
  cursor = { no_hardware_cursors = 1, inactive_timeout = 0 },
  misc = {
    disable_hyprland_logo = true,
    disable_splash_rendering = true,
    background_color = "rgb(1e1f29)",
    focus_on_activate = true,
  },
  ecosystem = { no_update_news = true, no_donation_nag = true },
})

-- A desktop rather than a tiling session: windows float and open centred.
hl.window_rule({ match = { class = ".*" }, float = true, center = true })
""")


class DeskError(RuntimeError):
    pass


def _pid_alive(pid):
    try:
        os.kill(pid, 0)
        return True
    except ProcessLookupError:
        return False
    except PermissionError:
        return True


def _parent(pid):
    try:
        stat = Path(f"/proc/{pid}/stat").read_text()
        return int(stat.rsplit(")", 1)[1].split()[1])
    except (OSError, ValueError, IndexError):
        return 0


def _descends_from(pid, ancestor):
    for _ in range(6):
        if pid == ancestor:
            return True
        pid = _parent(pid)
        if pid <= 1:
            return False
    return False


def _kill_group(pgid, timeout=3):
    for sig in (signal.SIGTERM, signal.SIGKILL):
        try:
            os.killpg(pgid, sig)
        except ProcessLookupError:
            return
        deadline = time.time() + timeout
        while time.time() < deadline:
            try:
                os.killpg(pgid, 0)
            except ProcessLookupError:
                return
            time.sleep(0.1)


def _lighten(hex_colour, amount=0.4):
    value = hex_colour.lstrip("#")
    rgb = [int(value[i : i + 2], 16) for i in (0, 2, 4)]
    return "".join(f"{round(c + (255 - c) * amount):02x}" for c in rgb)


class Desk:
    def __init__(self, cfg=None):
        self.cfg = cfg or settings.load()
        self.host = Hypr()
        self.state_path = settings.runtime_dir() / "state.json"

    # --- state -------------------------------------------------------------

    def state(self):
        if not self.state_path.exists():
            return None
        try:
            state = json.loads(self.state_path.read_text())
        except ValueError:
            state = {}
        alive = state.get("pid") and _pid_alive(state["pid"])
        known = any(i.get("instance") == state.get("instance") for i in instances())
        if not (alive and known):
            self.state_path.unlink(missing_ok=True)
            return None
        return state

    def require(self):
        state = self.state()
        if not state:
            raise DeskError("the agent desktop is not running; start it first")
        if not self.host.window(state["address"]):
            # The user closed the window; the nested session is useless now.
            self.stop()
            raise DeskError("the agent desktop window was closed; start it again")
        return state

    def sandbox(self, state=None):
        return Hypr((state or self.require())["instance"])

    def screen_size(self, state=None):
        monitors = self.sandbox(state).json("monitors")
        if not monitors:
            raise DeskError("the agent desktop has no screen")
        return monitors[0]["width"], monitors[0]["height"]

    # --- lifecycle ---------------------------------------------------------

    def start(self, show=None):
        require_host()
        state = self.state()
        if state:
            if show:
                self.show()
            return state

        if not shutil.which("Hyprland"):
            raise DeskError("Hyprland is not installed")
        runtime = settings.runtime_dir()
        icons = settings.data_dir() / "icons"
        cursor.ensure_theme(
            icons, self.cfg["accent"], self.cfg["label"],
            settings.DEFAULTS["accent"], settings.DEFAULTS["label"],
        )

        config_path = runtime / "hyprland.lua"
        config_path.write_text(SANDBOX_CONFIG.substitute(
            width=self.cfg["width"],
            height=self.cfg["height"],
            accent=self.cfg["accent"].lstrip("#"),
            kb_layout=self._host_option("input:kb_layout", "us"),
            kb_variant=self._host_option("input:kb_variant", ""),
        ))

        self._host_rule(enabled=True)
        try:
            proc, instance, window = self._launch(config_path, icons, runtime / "hyprland.log")
        finally:
            self._host_rule(enabled=False)

        state = {
            "pid": instance["pid"],
            "pgid": proc.pid,
            "instance": instance["instance"],
            "socket": instance["wl_socket"],
            "address": window["address"],
            "started": time.time(),
        }
        self.state_path.write_text(json.dumps(state))
        self.style_window(state)
        if show if show is not None else not self.cfg["start_hidden"]:
            self.show()
        return state

    def stop(self):
        if not self.state_path.exists():
            return False
        try:
            state = json.loads(self.state_path.read_text())
        except ValueError:
            state = {}
        self.state_path.unlink(missing_ok=True)
        pid, pgid = state.get("pid"), state.get("pgid")
        if not pid:
            return False
        try:
            Hypr(state["instance"]).dispatch("hl.dsp.exit()")
        except (HyprError, KeyError):
            pass
        deadline = time.time() + 3
        while time.time() < deadline and _pid_alive(pid):
            time.sleep(0.1)
        if pgid:
            _kill_group(pgid)
        return True

    # --- host window -------------------------------------------------------

    def _window(self, state):
        return f"address:{state['address']}"

    def visible(self, state=None):
        state = state or self.require()
        window = self.host.window(state["address"])
        return bool(window) and window["workspace"]["name"] != PARK_WORKSPACE

    def show(self):
        state = self.require()
        monitors = self.host.json("monitors")
        monitor = next((m for m in monitors if m.get("focused")), monitors[0])
        special = (monitor.get("specialWorkspace") or {}).get("name")
        if special:
            target = special
        else:
            active = monitor["activeWorkspace"]
            target = str(active["id"]) if active["id"] > 0 else "name:" + active["name"]
        window = self._window(state)
        self.host.dispatch("hl.dsp.window.move(" + lua_table(
            {"window": window, "workspace": target, "follow": False}) + ")")
        self.host.dispatch("hl.dsp.window.center(" + lua_table({"window": window}) + ")")
        self.host.dispatch("hl.dsp.window.alter_zorder(" + lua_table(
            {"window": window, "mode": "top"}) + ")")

    def hide(self):
        state = self.require()
        self.host.dispatch("hl.dsp.window.move(" + lua_table({
            "window": self._window(state),
            "workspace": "name:" + PARK_WORKSPACE,
            "follow": False,
        }) + ")")

    def toggle(self):
        if self.visible():
            self.hide()
            return False
        self.show()
        return True

    def style_window(self, state=None):
        state = state or self.require()
        window = self._window(state)
        accent = self.cfg["accent"].lstrip("#")
        frame = f"rgb({accent}) rgb({_lighten(accent)}) 45deg"
        props = [
            ("render_unfocused", 1),
            ("border_size", 3),
            ("active_border_color", frame),
            ("inactive_border_color", frame),
            ("no_dim", 1),
            ("opaque", 1),
        ]
        for prop, value in props:
            try:
                self.host.set_prop(window, prop, value)
            except HyprError:
                pass

    def ensure_rendering(self, state=None):
        """Re-apply render_unfocused if a host config reload dropped it."""
        state = state or self.require()
        window = self._window(state)
        if self.host.raw("getprop", window, "render_unfocused") != "true":
            self.style_window(state)

    # --- helpers -------------------------------------------------------------

    def _host_option(self, name, fallback):
        try:
            value = self.host.json("getoption", name).get("str", fallback)
        except HyprError:
            value = fallback
        return json.dumps(value or fallback)

    def _host_rule(self, enabled):
        # Applies only while our window maps: park it hidden, floating, at the
        # sandbox size, without stealing focus. Disabled right after start so
        # other nested Hyprland windows are left alone.
        rule = {
            "name": HOST_RULE,
            "enabled": enabled,
            "match": {"class": "^aquamarine$"},
            "float": True,
            "size": [self.cfg["width"], self.cfg["height"]],
            "workspace": f"name:{PARK_WORKSPACE} silent",
            "no_initial_focus": True,
            "render_unfocused": True,
        }
        try:
            self.host.eval(f"hl.window_rule({lua_table(rule)})")
        except HyprError:
            if enabled:
                raise

    def _spawn(self, config_path, icons, log_path):
        env = dict(os.environ)
        for key in ("HYPRCURSOR_THEME", "HYPRCURSOR_SIZE"):
            env.pop(key, None)
        env["XCURSOR_PATH"] = ":".join(filter(None, [
            str(icons), env.get("XCURSOR_PATH"), "/usr/share/icons",
            str(Path.home() / ".local/share/icons"),
        ]))
        env["XCURSOR_THEME"] = cursor.THEME_NAME
        env["XCURSOR_SIZE"] = "32"
        cmd = ["Hyprland", "--config", str(config_path)]
        if self.cfg["isolate_dbus"] and shutil.which("dbus-run-session"):
            cmd = ["dbus-run-session", "--"] + cmd
        with open(log_path, "w") as log:
            return subprocess.Popen(
                cmd, env=env, stdin=subprocess.DEVNULL, stdout=log,
                stderr=subprocess.STDOUT, start_new_session=True,
            )

    def _launch(self, config_path, icons, log_path, attempts=4):
        # The nested compositor sometimes cannot allocate GPU buffers right
        # after a previous one exited (seen on NVIDIA). Its window then never
        # maps, so give up on that attempt early and try again.
        error = None
        for attempt in range(attempts):
            if attempt:
                time.sleep(0.5 * attempt)
            proc = self._spawn(config_path, icons, log_path)
            try:
                instance = self._wait_for_instance(proc, log_path)
                window = self._wait_for_window(instance)
                return proc, instance, window
            except DeskError as exc:
                error = exc
                _kill_group(proc.pid)
        raise error

    def _wait_for_instance(self, proc, log_path, timeout=15):
        deadline = time.time() + timeout
        while time.time() < deadline:
            for inst in instances():
                if _descends_from(inst.get("pid", 0), proc.pid):
                    return inst
            if proc.poll() is not None:
                break
            time.sleep(0.2)
        tail = log_path.read_text()[-800:] if log_path.exists() else ""
        raise DeskError(f"the agent desktop did not start. Log tail:\n{tail}")

    def _wait_for_window(self, instance, timeout=4):
        log = Path(os.environ.get("XDG_RUNTIME_DIR", "/tmp")) / "hypr" / instance["instance"] / "hyprland.log"
        deadline = time.time() + timeout
        while time.time() < deadline:
            for client in self.host.clients():
                if client.get("pid") == instance["pid"]:
                    return client
            try:
                if "Swapchain: Failed acquiring a buffer" in log.read_text(errors="replace"):
                    raise DeskError("the agent desktop could not allocate GPU buffers")
            except OSError:
                pass
            time.sleep(0.2)
        raise DeskError("the agent desktop window never appeared on the host")
